/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssRouteImport } from './routes/rss'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as BentoRouteImport } from './routes/bento'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PinterestIndexRouteImport } from './routes/pinterest/index'
import { Route as CertificatesIndexRouteImport } from './routes/certificates/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as PinterestGalleryRouteImport } from './routes/pinterest/gallery'
import { Route as OgSiteRouteImport } from './routes/og/site'
import { Route as LlmsFullTxtRouteImport } from './routes/llms-full.txt'
import { Route as CertificatesSlugRouteImport } from './routes/certificates/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGamesRouteImport } from './routes/api/games'
import { Route as ApiCertificatesRouteImport } from './routes/api/certificates'
import { Route as OgProjectsSlugRouteImport } from './routes/og/projects/$slug'
import { Route as OgCertificatesSlugRouteImport } from './routes/og/certificates/$slug'
import { Route as OgBlogSlugRouteImport } from './routes/og/blog/$slug'
import { Route as ApiPinterestDownloadRouteImport } from './routes/api/pinterest.download'
import { Route as ApiGravatarIdentifierRouteImport } from './routes/api/gravatar.$identifier'

const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const BentoRoute = BentoRouteImport.update({
  id: '/bento',
  path: '/bento',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const PinterestIndexRoute = PinterestIndexRouteImport.update({
  id: '/pinterest/',
  path: '/pinterest/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PinterestGalleryRoute = PinterestGalleryRouteImport.update({
  id: '/pinterest/gallery',
  path: '/pinterest/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSiteRoute = OgSiteRouteImport.update({
  id: '/og/site',
  path: '/og/site',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullTxtRoute = LlmsFullTxtRouteImport.update({
  id: '/llms-full/txt',
  path: '/llms-full/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesSlugRoute = CertificatesSlugRouteImport.update({
  id: '/certificates/$slug',
  path: '/certificates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamesRoute = ApiGamesRouteImport.update({
  id: '/api/games',
  path: '/api/games',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesRoute = ApiCertificatesRouteImport.update({
  id: '/api/certificates',
  path: '/api/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const OgProjectsSlugRoute = OgProjectsSlugRouteImport.update({
  id: '/og/projects/$slug',
  path: '/og/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgCertificatesSlugRoute = OgCertificatesSlugRouteImport.update({
  id: '/og/certificates/$slug',
  path: '/og/certificates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgBlogSlugRoute = OgBlogSlugRouteImport.update({
  id: '/og/blog/$slug',
  path: '/og/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPinterestDownloadRoute = ApiPinterestDownloadRouteImport.update({
  id: '/api/pinterest/download',
  path: '/api/pinterest/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGravatarIdentifierRoute = ApiGravatarIdentifierRouteImport.update({
  id: '/api/gravatar/$identifier',
  path: '/api/gravatar/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bento': typeof BentoRoute
  '/readme': typeof ReadmeRoute
  '/resume': typeof ResumeRoute
  '/rss': typeof RssRoute
  '/api/certificates': typeof ApiCertificatesRoute
  '/api/games': typeof ApiGamesRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificates/$slug': typeof CertificatesSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/og/site': typeof OgSiteRoute
  '/pinterest/gallery': typeof PinterestGalleryRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/pinterest/': typeof PinterestIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/gravatar/$identifier': typeof ApiGravatarIdentifierRoute
  '/api/pinterest/download': typeof ApiPinterestDownloadRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
  '/og/certificates/$slug': typeof OgCertificatesSlugRoute
  '/og/projects/$slug': typeof OgProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bento': typeof BentoRoute
  '/readme': typeof ReadmeRoute
  '/resume': typeof ResumeRoute
  '/rss': typeof RssRoute
  '/api/certificates': typeof ApiCertificatesRoute
  '/api/games': typeof ApiGamesRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificates/$slug': typeof CertificatesSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/og/site': typeof OgSiteRoute
  '/pinterest/gallery': typeof PinterestGalleryRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog': typeof BlogIndexRoute
  '/certificates': typeof CertificatesIndexRoute
  '/pinterest': typeof PinterestIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/api/gravatar/$identifier': typeof ApiGravatarIdentifierRoute
  '/api/pinterest/download': typeof ApiPinterestDownloadRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
  '/og/certificates/$slug': typeof OgCertificatesSlugRoute
  '/og/projects/$slug': typeof OgProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bento': typeof BentoRoute
  '/readme': typeof ReadmeRoute
  '/resume': typeof ResumeRoute
  '/rss': typeof RssRoute
  '/api/certificates': typeof ApiCertificatesRoute
  '/api/games': typeof ApiGamesRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/certificates/$slug': typeof CertificatesSlugRoute
  '/llms-full/txt': typeof LlmsFullTxtRoute
  '/og/site': typeof OgSiteRoute
  '/pinterest/gallery': typeof PinterestGalleryRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/pinterest/': typeof PinterestIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/api/gravatar/$identifier': typeof ApiGravatarIdentifierRoute
  '/api/pinterest/download': typeof ApiPinterestDownloadRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
  '/og/certificates/$slug': typeof OgCertificatesSlugRoute
  '/og/projects/$slug': typeof OgProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bento'
    | '/readme'
    | '/resume'
    | '/rss'
    | '/api/certificates'
    | '/api/games'
    | '/api/health'
    | '/blog/$slug'
    | '/certificates/$slug'
    | '/llms-full/txt'
    | '/og/site'
    | '/pinterest/gallery'
    | '/projects/$slug'
    | '/sitemap/xml'
    | '/blog/'
    | '/certificates/'
    | '/pinterest/'
    | '/projects/'
    | '/api/gravatar/$identifier'
    | '/api/pinterest/download'
    | '/og/blog/$slug'
    | '/og/certificates/$slug'
    | '/og/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bento'
    | '/readme'
    | '/resume'
    | '/rss'
    | '/api/certificates'
    | '/api/games'
    | '/api/health'
    | '/blog/$slug'
    | '/certificates/$slug'
    | '/llms-full/txt'
    | '/og/site'
    | '/pinterest/gallery'
    | '/projects/$slug'
    | '/sitemap/xml'
    | '/blog'
    | '/certificates'
    | '/pinterest'
    | '/projects'
    | '/api/gravatar/$identifier'
    | '/api/pinterest/download'
    | '/og/blog/$slug'
    | '/og/certificates/$slug'
    | '/og/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bento'
    | '/readme'
    | '/resume'
    | '/rss'
    | '/api/certificates'
    | '/api/games'
    | '/api/health'
    | '/blog/$slug'
    | '/certificates/$slug'
    | '/llms-full/txt'
    | '/og/site'
    | '/pinterest/gallery'
    | '/projects/$slug'
    | '/sitemap/xml'
    | '/blog/'
    | '/certificates/'
    | '/pinterest/'
    | '/projects/'
    | '/api/gravatar/$identifier'
    | '/api/pinterest/download'
    | '/og/blog/$slug'
    | '/og/certificates/$slug'
    | '/og/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BentoRoute: typeof BentoRoute
  ReadmeRoute: typeof ReadmeRoute
  ResumeRoute: typeof ResumeRoute
  RssRoute: typeof RssRoute
  ApiCertificatesRoute: typeof ApiCertificatesRoute
  ApiGamesRoute: typeof ApiGamesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CertificatesSlugRoute: typeof CertificatesSlugRoute
  LlmsFullTxtRoute: typeof LlmsFullTxtRoute
  OgSiteRoute: typeof OgSiteRoute
  PinterestGalleryRoute: typeof PinterestGalleryRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  PinterestIndexRoute: typeof PinterestIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiGravatarIdentifierRoute: typeof ApiGravatarIdentifierRoute
  ApiPinterestDownloadRoute: typeof ApiPinterestDownloadRoute
  OgBlogSlugRoute: typeof OgBlogSlugRoute
  OgCertificatesSlugRoute: typeof OgCertificatesSlugRoute
  OgProjectsSlugRoute: typeof OgProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bento': {
      id: '/bento'
      path: '/bento'
      fullPath: '/bento'
      preLoaderRoute: typeof BentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinterest/': {
      id: '/pinterest/'
      path: '/pinterest'
      fullPath: '/pinterest/'
      preLoaderRoute: typeof PinterestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/certificates'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinterest/gallery': {
      id: '/pinterest/gallery'
      path: '/pinterest/gallery'
      fullPath: '/pinterest/gallery'
      preLoaderRoute: typeof PinterestGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/site': {
      id: '/og/site'
      path: '/og/site'
      fullPath: '/og/site'
      preLoaderRoute: typeof OgSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full/txt': {
      id: '/llms-full/txt'
      path: '/llms-full/txt'
      fullPath: '/llms-full/txt'
      preLoaderRoute: typeof LlmsFullTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/$slug': {
      id: '/certificates/$slug'
      path: '/certificates/$slug'
      fullPath: '/certificates/$slug'
      preLoaderRoute: typeof CertificatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/games': {
      id: '/api/games'
      path: '/api/games'
      fullPath: '/api/games'
      preLoaderRoute: typeof ApiGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates': {
      id: '/api/certificates'
      path: '/api/certificates'
      fullPath: '/api/certificates'
      preLoaderRoute: typeof ApiCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/projects/$slug': {
      id: '/og/projects/$slug'
      path: '/og/projects/$slug'
      fullPath: '/og/projects/$slug'
      preLoaderRoute: typeof OgProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/certificates/$slug': {
      id: '/og/certificates/$slug'
      path: '/og/certificates/$slug'
      fullPath: '/og/certificates/$slug'
      preLoaderRoute: typeof OgCertificatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/blog/$slug': {
      id: '/og/blog/$slug'
      path: '/og/blog/$slug'
      fullPath: '/og/blog/$slug'
      preLoaderRoute: typeof OgBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pinterest/download': {
      id: '/api/pinterest/download'
      path: '/api/pinterest/download'
      fullPath: '/api/pinterest/download'
      preLoaderRoute: typeof ApiPinterestDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gravatar/$identifier': {
      id: '/api/gravatar/$identifier'
      path: '/api/gravatar/$identifier'
      fullPath: '/api/gravatar/$identifier'
      preLoaderRoute: typeof ApiGravatarIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BentoRoute: BentoRoute,
  ReadmeRoute: ReadmeRoute,
  ResumeRoute: ResumeRoute,
  RssRoute: RssRoute,
  ApiCertificatesRoute: ApiCertificatesRoute,
  ApiGamesRoute: ApiGamesRoute,
  ApiHealthRoute: ApiHealthRoute,
  BlogSlugRoute: BlogSlugRoute,
  CertificatesSlugRoute: CertificatesSlugRoute,
  LlmsFullTxtRoute: LlmsFullTxtRoute,
  OgSiteRoute: OgSiteRoute,
  PinterestGalleryRoute: PinterestGalleryRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  PinterestIndexRoute: PinterestIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiGravatarIdentifierRoute: ApiGravatarIdentifierRoute,
  ApiPinterestDownloadRoute: ApiPinterestDownloadRoute,
  OgBlogSlugRoute: OgBlogSlugRoute,
  OgCertificatesSlugRoute: OgCertificatesSlugRoute,
  OgProjectsSlugRoute: OgProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
