/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RssRouteImport } from './routes/rss'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ReadmeRouteImport } from './routes/readme'
import { Route as BentoRouteImport } from './routes/bento'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as OgSiteRouteImport } from './routes/og/site'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as OgProjectsSlugRouteImport } from './routes/og/projects/$slug'
import { Route as OgBlogSlugRouteImport } from './routes/og/blog/$slug'

const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadmeRoute = ReadmeRouteImport.update({
  id: '/readme',
  path: '/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const BentoRoute = BentoRouteImport.update({
  id: '/bento',
  path: '/bento',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSiteRoute = OgSiteRouteImport.update({
  id: '/og/site',
  path: '/og/site',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const OgProjectsSlugRoute = OgProjectsSlugRouteImport.update({
  id: '/og/projects/$slug',
  path: '/og/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OgBlogSlugRoute = OgBlogSlugRouteImport.update({
  id: '/og/blog/$slug',
  path: '/og/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bento': typeof BentoRoute
  '/readme': typeof ReadmeRoute
  '/resume': typeof ResumeRoute
  '/rss': typeof RssRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/og/site': typeof OgSiteRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
  '/og/projects/$slug': typeof OgProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bento': typeof BentoRoute
  '/readme': typeof ReadmeRoute
  '/resume': typeof ResumeRoute
  '/rss': typeof RssRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/og/site': typeof OgSiteRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
  '/og/projects/$slug': typeof OgProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bento': typeof BentoRoute
  '/readme': typeof ReadmeRoute
  '/resume': typeof ResumeRoute
  '/rss': typeof RssRoute
  '/api/health': typeof ApiHealthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/og/site': typeof OgSiteRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/og/blog/$slug': typeof OgBlogSlugRoute
  '/og/projects/$slug': typeof OgProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bento'
    | '/readme'
    | '/resume'
    | '/rss'
    | '/api/health'
    | '/blog/$slug'
    | '/og/site'
    | '/projects/$slug'
    | '/sitemap/xml'
    | '/blog/'
    | '/projects/'
    | '/og/blog/$slug'
    | '/og/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bento'
    | '/readme'
    | '/resume'
    | '/rss'
    | '/api/health'
    | '/blog/$slug'
    | '/og/site'
    | '/projects/$slug'
    | '/sitemap/xml'
    | '/blog'
    | '/projects'
    | '/og/blog/$slug'
    | '/og/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/bento'
    | '/readme'
    | '/resume'
    | '/rss'
    | '/api/health'
    | '/blog/$slug'
    | '/og/site'
    | '/projects/$slug'
    | '/sitemap/xml'
    | '/blog/'
    | '/projects/'
    | '/og/blog/$slug'
    | '/og/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BentoRoute: typeof BentoRoute
  ReadmeRoute: typeof ReadmeRoute
  ResumeRoute: typeof ResumeRoute
  RssRoute: typeof RssRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  OgSiteRoute: typeof OgSiteRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  OgBlogSlugRoute: typeof OgBlogSlugRoute
  OgProjectsSlugRoute: typeof OgProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readme': {
      id: '/readme'
      path: '/readme'
      fullPath: '/readme'
      preLoaderRoute: typeof ReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bento': {
      id: '/bento'
      path: '/bento'
      fullPath: '/bento'
      preLoaderRoute: typeof BentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/site': {
      id: '/og/site'
      path: '/og/site'
      fullPath: '/og/site'
      preLoaderRoute: typeof OgSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/projects/$slug': {
      id: '/og/projects/$slug'
      path: '/og/projects/$slug'
      fullPath: '/og/projects/$slug'
      preLoaderRoute: typeof OgProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/blog/$slug': {
      id: '/og/blog/$slug'
      path: '/og/blog/$slug'
      fullPath: '/og/blog/$slug'
      preLoaderRoute: typeof OgBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BentoRoute: BentoRoute,
  ReadmeRoute: ReadmeRoute,
  ResumeRoute: ResumeRoute,
  RssRoute: RssRoute,
  ApiHealthRoute: ApiHealthRoute,
  BlogSlugRoute: BlogSlugRoute,
  OgSiteRoute: OgSiteRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  OgBlogSlugRoute: OgBlogSlugRoute,
  OgProjectsSlugRoute: OgProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
